name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install flask
        pip install selenium
        pip install pytest
        pip install webdriver-manager
        pip install requests  # Add this line to install the requests library for API testing

    - name: Start Flask server
      run: |
        python app.py &
      env:
        FLASK_ENV: development

    - name: Run tests
      run: |
        pytest tests/test_app.py  
        pytest tests/test_api.py  

